import Conf from "conf";
import { execSync, spawn } from "child_process";
import { existsSync, readFileSync } from "fs";
import { resolve, join } from "path";
import chalk from "chalk";

// Persistent config store (stored in OS config dir)
export const config = new Conf({
  projectName: "synthclaw",
  schema: {
    interface_mode: { type: "string", default: "telegram" },
    telegram_token: { type: "string", default: "" },
    whatsapp_token: { type: "string", default: "" },
    whatsapp_phone_number_id: { type: "string", default: "" },
    whatsapp_verify_token: { type: "string", default: "" },
    whatsapp_port: { type: "string", default: "8443" },
    openai_api_key: { type: "string", default: "" },
    openai_api_base: {
      type: "string",
      default: "https://inference.do-ai.run/v1",
    },
    default_model: { type: "string", default: "llama3.3-70b-instruct" },
    base_dir: { type: "string", default: "/opt/agent" },
    max_tool_iterations: { type: "string", default: "10" },
    max_history_messages: { type: "string", default: "20" },
    remote_host: { type: "string", default: "" },
    remote_user: { type: "string", default: "root" },
  },
});

/**
 * Get the project root (where the Python agent files live).
 * Walks up from cli/ to find main.py.
 */
export function getProjectRoot() {
  // When installed globally via npm link, the project root is ../
  let dir = new URL(".", import.meta.url).pathname;
  // Walk up to find main.py
  for (let i = 0; i < 5; i++) {
    if (existsSync(join(dir, "main.py"))) return dir;
    dir = resolve(dir, "..");
  }
  // Fallback: base_dir from config
  const baseDir = config.get("base_dir");
  if (existsSync(join(baseDir, "main.py"))) return baseDir;
  return process.cwd();
}

/**
 * Generate .env content from current config.
 */
export function generateEnvContent() {
  const lines = [
    "# SynthClaw-CoAgent Configuration",
    "# Generated by: synthclaw setup",
    "",
    `INTERFACE_MODE="${config.get("interface_mode")}"`,
    "",
  ];

  if (
    config.get("interface_mode") === "telegram" ||
    config.get("interface_mode") === "both"
  ) {
    lines.push(`TELEGRAM_TOKEN="${config.get("telegram_token")}"`);
    lines.push("");
  }

  if (
    config.get("interface_mode") === "whatsapp" ||
    config.get("interface_mode") === "both"
  ) {
    lines.push(`WHATSAPP_TOKEN="${config.get("whatsapp_token")}"`);
    lines.push(
      `WHATSAPP_PHONE_NUMBER_ID="${config.get("whatsapp_phone_number_id")}"`
    );
    lines.push(`WHATSAPP_VERIFY_TOKEN="${config.get("whatsapp_verify_token")}"`);
    lines.push(`WHATSAPP_PORT="${config.get("whatsapp_port")}"`);
    lines.push("");
  }

  lines.push(`OPENAI_API_KEY="${config.get("openai_api_key")}"`);
  lines.push(`OPENAI_API_BASE="${config.get("openai_api_base")}"`);
  lines.push(`DEFAULT_MODEL="${config.get("default_model")}"`);
  lines.push("");
  lines.push(`SYNTHCLAW_BASE_DIR="${config.get("base_dir")}"`);
  lines.push(`MAX_TOOL_ITERATIONS="${config.get("max_tool_iterations")}"`);
  lines.push(`MAX_HISTORY_MESSAGES="${config.get("max_history_messages")}"`);
  lines.push("");

  return lines.join("\n");
}

/**
 * Run a command on the remote host via SSH (if configured) or locally.
 */
export function remoteExec(cmd, options = {}) {
  const host = config.get("remote_host");
  const user = config.get("remote_user") || "root";

  if (host) {
    const sshCmd = `ssh ${user}@${host} '${cmd.replace(/'/g, "'\\''")}'`;
    return execSync(sshCmd, {
      encoding: "utf-8",
      timeout: options.timeout || 30000,
      ...options,
    });
  } else {
    return execSync(cmd, {
      encoding: "utf-8",
      timeout: options.timeout || 30000,
      ...options,
    });
  }
}

/**
 * Check if the agent process is running.
 */
export function isAgentRunning() {
  try {
    const result = remoteExec("systemctl is-active agent 2>/dev/null || echo inactive");
    return result.trim() === "active";
  } catch {
    return false;
  }
}

export function printError(msg) {
  console.error(chalk.red("✗ ") + msg);
}

export function printSuccess(msg) {
  console.log(chalk.green("✓ ") + msg);
}

export function printInfo(msg) {
  console.log(chalk.blue("ℹ ") + msg);
}
