import Conf from "conf";
import { execSync, spawn } from "child_process";
import { existsSync, readFileSync } from "fs";
import { resolve, join } from "path";
import chalk from "chalk";

// Persistent config store (stored in OS config dir)
export const config = new Conf({
  projectName: "synthclaw",
  schema: {
    interface_mode: { type: "string", default: "telegram" },
    telegram_token: { type: "string", default: "" },
    whatsapp_token: { type: "string", default: "" },
    whatsapp_phone_number_id: { type: "string", default: "" },
    whatsapp_verify_token: { type: "string", default: "" },
    whatsapp_port: { type: "string", default: "8443" },
    openai_api_key: { type: "string", default: "" },
    openai_api_base: {
      type: "string",
      default: "https://inference.do-ai.run/v1",
    },
    default_model: { type: "string", default: "llama3.3-70b-instruct" },
    base_dir: { type: "string", default: "/opt/agent" },
    max_tool_iterations: { type: "string", default: "10" },
    max_history_messages: { type: "string", default: "20" },
    remote_host: { type: "string", default: "" },
    remote_user: { type: "string", default: "root" },
    max_rpm: { type: "string", default: "0" },
    composio_api_key: { type: "string", default: "" },
    storage_mode: { type: "string", default: "local" },
    cf_account_id: { type: "string", default: "" },
    cf_d1_database_id: { type: "string", default: "" },
    cf_api_token: { type: "string", default: "" },
    cf_r2_bucket: { type: "string", default: "" },
  },
});

/**
 * Get the project root (where the Python agent files live).
 * Checks multiple locations in priority order.
 */
export function getProjectRoot() {
  // 1. Check current working directory
  if (existsSync(join(process.cwd(), "main.py"))) return process.cwd();

  // 2. Walk up from the source file location (works when running from cli/src)
  let dir = new URL(".", import.meta.url).pathname;
  for (let i = 0; i < 5; i++) {
    if (existsSync(join(dir, "main.py"))) return dir;
    dir = resolve(dir, "..");
  }

  // 3. Check base_dir from config
  const baseDir = config.get("base_dir");
  if (existsSync(join(baseDir, "main.py"))) return baseDir;

  // 4. Common install paths
  const commonPaths = [
    join(process.env.HOME || "/root", "synthclaw"),
    join(process.env.HOME || "/root", "synthclaw-coagent"),
    "/opt/agent",
    "/root/synthclaw",
    "/root/synthclaw-coagent",
  ];
  for (const p of commonPaths) {
    if (existsSync(join(p, "main.py"))) return p;
  }

  return process.cwd();
}

/**
 * Generate .env content from current config.
 * IMPORTANT: No quotes around values! systemd EnvironmentFile treats quotes as literal.
 * Also used by python-dotenv which handles both quoted/unquoted, but unquoted is safest.
 */
export function generateEnvContent() {
  const lines = [
    "# SynthClaw-CoAgent Configuration",
    "# Generated by: synthclaw setup",
    "",
    `INTERFACE_MODE=${config.get("interface_mode")}`,
    "",
  ];

  if (
    config.get("interface_mode") === "telegram" ||
    config.get("interface_mode") === "both"
  ) {
    lines.push(`TELEGRAM_TOKEN=${config.get("telegram_token")}`);
    lines.push("");
  }

  if (
    config.get("interface_mode") === "whatsapp" ||
    config.get("interface_mode") === "both"
  ) {
    lines.push(`WHATSAPP_TOKEN=${config.get("whatsapp_token")}`);
    lines.push(
      `WHATSAPP_PHONE_NUMBER_ID=${config.get("whatsapp_phone_number_id")}`
    );
    lines.push(`WHATSAPP_VERIFY_TOKEN=${config.get("whatsapp_verify_token")}`);
    lines.push(`WHATSAPP_PORT=${config.get("whatsapp_port")}`);
    lines.push("");
  }

  lines.push(`OPENAI_API_KEY=${config.get("openai_api_key")}`);
  lines.push(`OPENAI_API_BASE=${config.get("openai_api_base")}`);
  lines.push(`DEFAULT_MODEL=${config.get("default_model")}`);
  lines.push("");
  // Use actual project root for SYNTHCLAW_BASE_DIR (not the config default)
  // This ensures Python finds agent.log, agent.db, workspace/ in the right place
  const actualRoot = getProjectRoot();
  lines.push(`SYNTHCLAW_BASE_DIR=${actualRoot}`);
  lines.push(`MAX_TOOL_ITERATIONS=${config.get("max_tool_iterations")}`);
  lines.push(`MAX_HISTORY_MESSAGES=${config.get("max_history_messages")}`);
  const rpm = config.get("max_rpm") || "0";
  if (rpm && rpm !== "0") {
    lines.push(`MAX_RPM=${rpm}`);
  }
  if (config.get("composio_api_key")) {
    lines.push(`COMPOSIO_API_KEY=${config.get("composio_api_key")}`);
  }
  if (config.get("storage_mode") === "cloudflare") {
    lines.push(`STORAGE_MODE=cloudflare`);
    lines.push(`CF_ACCOUNT_ID=${config.get("cf_account_id")}`);
    lines.push(`CF_D1_DATABASE_ID=${config.get("cf_d1_database_id")}`);
    lines.push(`CF_API_TOKEN=${config.get("cf_api_token")}`);
    if (config.get("cf_r2_bucket")) {
      lines.push(`CF_R2_BUCKET=${config.get("cf_r2_bucket")}`);
    }
  }
  lines.push("");

  return lines.join("\n");
}

/**
 * Run a command on the remote host via SSH (if configured) or locally.
 */
export function remoteExec(cmd, options = {}) {
  const host = config.get("remote_host");
  const user = config.get("remote_user") || "root";

  if (host) {
    const sshCmd = `ssh ${user}@${host} '${cmd.replace(/'/g, "'\\''")}'`;
    return execSync(sshCmd, {
      encoding: "utf-8",
      timeout: options.timeout || 30000,
      ...options,
    });
  } else {
    return execSync(cmd, {
      encoding: "utf-8",
      timeout: options.timeout || 30000,
      ...options,
    });
  }
}

/**
 * Check if the agent process is running.
 */
export function isAgentRunning() {
  try {
    const result = remoteExec("systemctl is-active agent 2>/dev/null || echo inactive");
    return result.trim() === "active";
  } catch {
    return false;
  }
}

export function printError(msg) {
  console.error(chalk.red("✗ ") + msg);
}

export function printSuccess(msg) {
  console.log(chalk.green("✓ ") + msg);
}

export function printInfo(msg) {
  console.log(chalk.blue("ℹ ") + msg);
}
